# Set up Environment

In [54]:
!pip install datasets
!pip install nvcc4jupyter

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (0.1.2)
Collecting nvcc4jupyter
  Downloading nvcc4jupyter-1.2.1-py3-none-any.whl.metadata (5.1 kB)
Downloading nvcc4jupyter-1.2.1-py3-none-any.whl (10 kB)
Installing collected packages: nvcc4jupyter
Successfully installed nvcc4jupyter-1.2.1

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Sat May  2 21:34:54 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   37C    P0             57W /  400W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
!python --version

Python 3.12.13

In [55]:
%load_ext nvcc4jupyter

Detected platform "Colab". Running its setup...
Source files will be saved in "/tmp/tmp1is14p9e".

In [56]:
import subprocess
import tempfile
import os

# Load Dataset

In [5]:
import pandas as pd

df = pd.read_json("hf://datasets/nvidia/compute-eval/data/problems.jsonl", lines=True)

### Analyze dataset

In [5]:
df.head(2)

,type,schema_version,task_id,date,prompt,metadata,group,context_files,test_files,source_references,build_command,test_command,benchmark_command,timing_mode,min_cuda_toolkit,compute_capability,requires_datacenter_gpu,timeout_seconds,baseline_solution
0,cuda_cpp,2,CUDA/146,2025-10-31,Develop a CUDA program using the Thrust API to...,"{'difficulty': 'medium', 'tags': ['thrust', 'b...",cccl,"[{'path': 'include/find_indices.h', 'content':...","[{'path': 'test/test_main.cu', 'content': '#in...",None,nvcc -I include -o test.out solution.cu test/*.cu,./test.out,./test.out --perf,"{'type': 'region', 'include': ['bench_region']...",12.2,NaN,False,120,"{'schema_version': 1, 'type': 'file', 'task_id..."
1,cuda_cpp,2,CUDA/151,2025-11-05,Write a CUDA kernel to test the primality of a...,"{'difficulty': 'hard', 'tags': ['miller-rabin'...",cccl,"[{'path': 'helper.cu', 'content': '#include ""m...","[{'path': 'test/test_main.cu', 'content': '#in...",None,nvcc -I include -o test.out solution.cu helper...,./test.out,./test.out --perf,"{'type': 'region', 'include': ['bench_region']...",12.2,NaN,False,120,"{'schema_version': 1, 'type': 'file', 'task_id..."

In [ ]:
df['task_id'].isna().values.any()

np.False_

In [ ]:
df['baseline_solution'].iloc[0]

{'schema_version': 1,
 'type': 'file',
 'task_id': 'CUDA/146',
 'files': [{'path': 'solution.cu',
   'content': '#include <thrust/sequence.h>\n#include <thrust/sort.h>\n#include <thrust/binary_search.h>\n#include <thrust/gather.h>\n#include <thrust/for_each.h>\n#include <thrust/device_vector.h>\n\n#include "find_indices.h"\n\nthrust::device_vector<int> findIndices(const thrust::device_vector<int>& inputArray_d, const thrust::device_vector<int>& testData_d) {\n    // Index mapping for the input array\n    thrust::device_vector<int> indices_d(inputArray_d.size());\n    thrust::sequence(indices_d.begin(), indices_d.end());\n\n    // Copy data for sorting\n    thrust::device_vector<int> sortedInputArray_d = inputArray_d;\n    thrust::device_vector<int> sortedInputIndices_d = indices_d;\n\n    // Sort input array along with the indices\n    thrust::sort_by_key(sortedInputArray_d.begin(), sortedInputArray_d.end(), sortedInputIndices_d.begin());\n          \n    // Perform binary search and return the indices of the test data\n    thrust::device_vector<int> testIndices_d(testData_d.size());\n    thrust::lower_bound(sortedInputArray_d.begin(), sortedInputArray_d.end(), testData_d.begin(), testData_d.end(), testIndices_d.begin());\n\n    //result vector to store the test indices\n    thrust::device_vector<int> result_d(testData_d.size());\n\n    // Maps the test index with the input index and store in result\n    thrust::gather(testIndices_d.begin(), testIndices_d.end(), sortedInputIndices_d.begin(), result_d.begin());\n\n    // The indices of the test data not in the input have to be updated to default value.\n    // Functor indexUpdate is called to update the index value.\n    thrust::for_each(thrust::counting_iterator<int>(0),\n                    thrust::counting_iterator<int>(testData_d.size()),\n                    indexUpdate(thrust::raw_pointer_cast(result_d.data()), \n                    thrust::raw_pointer_cast(testData_d.data()),\n                    thrust::raw_pointer_cast(sortedInputArray_d.data()), \n                    thrust::raw_pointer_cast(testIndices_d.data()),\n                    sortedInputArray_d.size()) \n                    );\n    return result_d;\n}'}]}

In [12]:
prompts = df['prompt'].tolist()

In [15]:
len(prompts)

566

# Generate Results

## Remote Inference via Providers
- Openai provider

### Model Info
- Open AI models
  - name: `gpt-5.5`
  - api: responses api

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.32.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [ ]:
import os
from getpass import getpass

os.environ['OPENAI_API_KEY'] = getpass('Enter your OpenAI API Key: ')

Enter your OpenAI API Key: ··········

In [ ]:
from openai import OpenAI, AsyncOpenAI

client = OpenAI()

In [ ]:
def invoke_llm(prompt: str) -> str:
  response = client.responses.create(
    model="gpt-5.5",
    input = prompt
  )

  return response.output_text

In [ ]:
df_remain = df.loc[169:]

In [ ]:
len(df_remain)

397

In [ ]:
generated_response = []

for index, input_row in df_remain.iterrows():
  problem_row =input_row
  result = invoke_llm(input_row['prompt'])
  generated_response.append(result)
  print('current task ==> ' + input_row['task_id'])

df['generated_response'] = generated_response

current task ==> CUDA/11
current task ==> CUDA/110
current task ==> CUDA/111
current task ==> CUDA/112
current task ==> CUDA/113
current task ==> CUDA/114
current task ==> CUDA/115
current task ==> CUDA/116
current task ==> CUDA/117
current task ==> CUDA/118
current task ==> CUDA/119
current task ==> CUDA/12
current task ==> CUDA/120
current task ==> CUDA/121
current task ==> CUDA/122
current task ==> CUDA/123
current task ==> CUDA/124
current task ==> CUDA/125
current task ==> CUDA/126
current task ==> CUDA/127
current task ==> CUDA/128
current task ==> CUDA/129
current task ==> CUDA/130
current task ==> CUDA/131
current task ==> CUDA/132
current task ==> CUDA/133
current task ==> CUDA/134
current task ==> CUDA/135
current task ==> CUDA/136
current task ==> CUDA/137
current task ==> CUDA/138
current task ==> CUDA/139
current task ==> CUDA/14
current task ==> CUDA/140
current task ==> CUDA/141
current task ==> CUDA/142
current task ==> CUDA/143
current task ==> CUDA/144
current task ==> CUDA/145
current task ==> CUDA/147
current task ==> CUDA/148
current task ==> CUDA/15
current task ==> CUDA/153
current task ==> CUDA/158
current task ==> CUDA/163
current task ==> CUDA/165
current task ==> CUDA/166
current task ==> CUDA/167
current task ==> CUDA/168
current task ==> CUDA/169
current task ==> CUDA/17
current task ==> CUDA/172
current task ==> CUDA/173
current task ==> CUDA/174
current task ==> CUDA/18
current task ==> CUDA/185
current task ==> CUDA/189
current task ==> CUDA/190
current task ==> CUDA/191
current task ==> CUDA/193
current task ==> CUDA/194
current task ==> CUDA/195
current task ==> CUDA/197
current task ==> CUDA/198
current task ==> CUDA/20
current task ==> CUDA/200
current task ==> CUDA/201
current task ==> CUDA/203
current task ==> CUDA/204
current task ==> CUDA/207
current task ==> CUDA/209
current task ==> CUDA/21
current task ==> CUDA/211
current task ==> CUDA/212
current task ==> CUDA/215
current task ==> CUDA/216
current task ==> CUDA/217
current task ==> CUDA/218
current task ==> CUDA/219
current task ==> CUDA/22
current task ==> CUDA/220
current task ==> CUDA/221
current task ==> CUDA/222
current task ==> CUDA/223
current task ==> CUDA/224
current task ==> CUDA/225
current task ==> CUDA/226
current task ==> CUDA/227
current task ==> CUDA/229
current task ==> CUDA/230
current task ==> CUDA/231
current task ==> CUDA/25
current task ==> CUDA/26
current task ==> CUDA/27

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
len(generated_response)

169

In [ ]:
df.head(2)

,type,schema_version,task_id,date,prompt,metadata,group,context_files,test_files,source_references,build_command,test_command,benchmark_command,timing_mode,min_cuda_toolkit,compute_capability,requires_datacenter_gpu,timeout_seconds,baseline_solution,generated_response
0,cuda_cpp,2,CUDA/146,2025-10-31,Develop a CUDA program using the Thrust API to...,"{'difficulty': 'medium', 'tags': ['thrust', 'b...",cccl,"[{'path': 'include/find_indices.h', 'content':...","[{'path': 'test/test_main.cu', 'content': '#in...",None,nvcc -I include -o test.out solution.cu test/*.cu,./test.out,./test.out --perf,"{'type': 'region', 'include': ['bench_region']...",12.2,NaN,False,120,"{'schema_version': 1, 'type': 'file', 'task_id...","```cpp\n// solution.cu\n\n#include ""include/fi..."
1,cuda_cpp,2,CUDA/151,2025-11-05,Write a CUDA kernel to test the primality of a...,"{'difficulty': 'hard', 'tags': ['miller-rabin'...",cccl,"[{'path': 'helper.cu', 'content': '#include ""m...","[{'path': 'test/test_main.cu', 'content': '#in...",None,nvcc -I include -o test.out solution.cu helper...,./test.out,./test.out --perf,"{'type': 'region', 'include': ['bench_region']...",12.2,NaN,False,120,"{'schema_version': 1, 'type': 'file', 'task_id...","```cuda\n// solution.cu\n\n#include ""miller_ra..."

### Python Concurrency

#### AsyncIO
The asyncio module is particularly useful for I/O-bound tasks like network requests, where you need to perform many operations concurrently but not necessarily in parallel. It enables concurrent execution within a single thread through cooperative multitasking.

#### MultiProcessing
from multiprocessing import Pool, Process
```
def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))

    p = Process(target=f, args=('b', ))
    p.start()
    p.join()
```
Never use subprocess or multiprocessing for API calls — they add process-spawning overhead to what is purely an I/O-bound network task. You get none of the CPU-parallelism benefits and all of the costs.

In [ ]:
'''
The Async Solution, cell is not geting the async result
'''
# from openai import AsyncOpenAI
# import asyncio
# import nest_asyncio

# async_client = AsyncOpenAI()

# async def invoke_async_llm(prompt: str) -> str:
#   response = await async_client.responses.create(
#       model="gpt-5.5",
#       input = prompt
#   )
#   return response.text


# remaining_results = []

# async def async_main(prompts:list):
#   sem = asyncio.Semaphore(10)
#   async def bounded_call(p):
#     async with sem:
#       return await invoke_async_llm(p)
#   results = await asyncio.gather(*[bounded_call(p) for p in prompts])
#   print(f"All {len(results)} completed")
#   return results


# nest_asyncio.apply()
# prompts = df.to_numpy().tolist()
# results = asyncio.get_event_loop().run_until_complete(async_main(prompts))

### OpenAI batch API

## Local Inference on GPU

- transformer
- vllm

### Transformers

In [3]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [5]:
!pip install compressed-tensors

Requirement already satisfied: compressed-tensors in /usr/local/lib/python3.12/dist-packages (0.15.0.1)
Requirement already satisfied: torch>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from compressed-tensors) (2.10.0+cu128)
Requirement already satisfied: transformers>=4.45.0 in /usr/local/lib/python3.12/dist-packages (from compressed-tensors) (4.57.1)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from compressed-tensors) (2.12.3)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from compressed-tensors) (0.7.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->compressed-tensors) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->compressed-tensors) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->compressed-tensors) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->compressed-tensors) (0.4.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.7.0->compressed-tensors) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.7.0->compressed-tensors) (1.5.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->compressed-tensors) (4.67.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.45.0->compressed-tensors) (1.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.7.0->compressed-tensors) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.7.0->compressed-tensors) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.45.0->compressed-tensors) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.45.0->compressed-tensors) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.45.0->compressed-tensors) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.45.0->compressed-tensors) (2026.4.22)

In [3]:
import os
from getpass import getpass

os.environ['HF_TOKEN'] = getpass('Enter your OpenAI API Key: ')

Enter your OpenAI API Key: ··········

In [1]:
from transformers import AutoModel
model = AutoModel.from_pretrained("openai/gpt-oss-20b", trust_remote_code=True, dtype="auto")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

MXFP4 quantization requires Triton and kernels installed: CUDA requires Triton >= 3.4.0, XPU requires Triton >= 3.5.0, we will default to dequantizing the model to bf16

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00000-of-00002.safetensors:   0%|          | 0.00/4.79G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/4.17G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.80G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [2]:
from transformers import AutoTokenizer
import torch

# Load the tokenizer for the model
tokenizer = AutoTokenizer.from_pretrained("openai/gpt-oss-20b")

# Example input text
input_text = "Hello, how are you today?"

# Tokenize the input text
# If the model expects `input_ids` and `attention_mask`,
# `return_tensors="pt"` will return PyTorch tensors.
inputs = tokenizer(input_text, return_tensors="pt")

# Move inputs to the appropriate device (e.g., GPU if available)
if torch.cuda.is_available():
    model.to("cuda")
    inputs = {k: v.to("cuda") for k, v in inputs.items()}

# Pass the tokenized inputs to the model
# The output will depend on the model's task (e.g., causal language modeling, sequence classification)
with torch.no_grad(): # Disable gradient calculation for inference
    outputs = model(**inputs)

print("Model inputs:", inputs)
print("Model outputs (first 50 characters of logits shape if available, or just outputs):\n", outputs.logits.shape if hasattr(outputs, 'logits') else outputs)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/98.0 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Model inputs: {'input_ids': tensor([[13225,    11,  1495,   553,   481,  4044,    30]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}
Model outputs (first 50 characters of logits shape if available, or just outputs):
 MoeModelOutputWithPast(last_hidden_state=tensor([[[ -7.9062,   5.5625,   3.7188,  ...,  -2.9219,   2.3438, -17.5000],
         [-11.3750,   1.4531,  -1.2344,  ...,  -0.5703,   0.4316, -11.8125],
         [ -2.9688,  -0.6367,   0.6875,  ...,   0.2363,  -0.3086, -13.5625],
         ...,
         [-13.6875,   2.6250,  -2.4531,  ...,   4.8750,   0.2344,  -5.7500],
         [-10.7500,   2.2969,  -2.0312,  ...,   3.2656,  -0.1216,  -2.1562],
         [ -9.8125,   1.2734,   1.7734,  ...,   0.2324,   1.8359,  -2.2656]]],
       device='cuda:0', dtype=torch.bfloat16), past_key_values=DynamicCache(layers=[DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer]), hidden_states=None, attentions=None, router_logits=None)

In [9]:
outputs

MoeModelOutputWithPast(last_hidden_state=tensor([[[ -7.9062,   5.5625,   3.7188,  ...,  -2.9219,   2.3438, -17.5000],
         [-11.3750,   1.4531,  -1.2344,  ...,  -0.5703,   0.4316, -11.8125],
         [ -2.9688,  -0.6367,   0.6875,  ...,   0.2363,  -0.3086, -13.5625],
         ...,
         [-13.6875,   2.6250,  -2.4531,  ...,   4.8750,   0.2344,  -5.7500],
         [-10.7500,   2.2969,  -2.0312,  ...,   3.2656,  -0.1216,  -2.1562],
         [ -9.8125,   1.2734,   1.7734,  ...,   0.2324,   1.8359,  -2.2656]]],
       device='cuda:0', dtype=torch.bfloat16), past_key_values=DynamicCache(layers=[DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer, DynamicSlidingWindowLayer, DynamicLayer]), hidden_states=None, attentions=None, router_logits=None)

In [ ]:
# TODO output tensor to text

In [ ]:
prompts

In [6]:
concat_prompts = []

for index, input_row in df.iterrows():
  input_dict = {}
  input_dict["role"] = "user"
  input_dict["content"] = input_row['prompt']
  concat_prompts.append(input_dict)

In [11]:
concat_prompts_firstpart = concat_prompts[:100]
concat_prompts_secondpart = concat_prompts[100:200]
concat_prompts_thirdpart = concat_prompts[200:300]
concat_prompts_fourthpart = concat_prompts[300:400]
concat_prompts_fifthpart = concat_prompts[400:]

In [15]:
concat_prompt_list = []
concat_prompt_list.append(concat_prompts_firstpart)
concat_prompt_list.append(concat_prompts_secondpart)
concat_prompt_list.append(concat_prompts_thirdpart)
concat_prompt_list.append(concat_prompts_fourthpart)
concat_prompt_list.append(concat_prompts_fifthpart)

In [19]:
concat_prompts_firstpart

[{'role': 'user',
  'content': 'Develop a CUDA program using the Thrust API to search for a set of elements within an input array and return their corresponding indices. If multiple occurrences of an element exist in the input array, the index of its first occurrence will be returned; if an element is not found, -1 will be returned.\n\nYour implementation must be in `solution.cu` and use the contract defined in `include/find_indices.h`.\n\n**Function Signature:**\n```cpp\nthrust::device_vector<int> findIndices(const thrust::device_vector<int>& inputArray_d,\n                                       const thrust::device_vector<int>& testData_d);\n```\n\n**Parameters:**\n- `inputArray_d`: The source/input array (unsorted)\n- `testData_d`: Elements to search for in inputArray_d\n\n**Returns:**\n- A device vector containing the index of each testData_d element in inputArray_d if found, -1 otherwise\n\n**Functor (defined in header):**\n- `struct indexUpdate`: Contains a device operator that updates the result vector with -1 for elements not found\n- `__device__ void operator()(int i)`: Where `i` is the index of the test data element being checked\n\n**Examples:**\n```cpp\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {2, 3, 81, 46})\n// Output: {2, 40, 16, -1}\n\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {34, 87, 12, 59, 3, 76, 41, 68, 25, 93})\n// Output: {28, -1, 48, 39, 40, 14, -1, 30, -1, 4}\n```'},
 {'role': 'user',
  'content': "Write a CUDA kernel to test the primality of a list of numbers using the Miller-Rabin algorithm.\nThe kernel should be launched with different configurations of blocksize.\n\nYour implementation must be in `solution.cu` and include `miller_rabin.h`. Implement the following kernel signature:\n\n```cuda\n__global__ void k_millerRabin(unsigned long long *inputNumbers, unsigned long long *primalityResults, int numberOfElements);\n```\n\nWhere:\n- `inputNumbers`: array of input numbers to be tested for primality\n- `primalityResults`: pointer to the array where the primality test results will be stored (the number is stored if prime, else 0 if composite)\n- `numberOfElements`: total number of inputNumbers\n\n**Parallelization Requirements:**\n\nThe kernel must use warp-level cooperative parallelism where each warp collectively tests a single number.\nWithin each warp, different threads must test the same number against different witnesses (base values) in parallel.\nEach thread should select its witness based on its position within the warp, starting from base 2 and incrementing for each subsequent thread.\nAll threads in a warp must agree on primality for the number to be considered prime.\n\nThe kernel should use dynamic shared memory for coordination within each block.\nYou'll need to store intermediate Miller-Rabin decomposition values that can be shared across threads in the same warp.\nThe helper function `dynamicSMemSizeMillerRabin` computes the required shared memory size.\n\nEach warp processes one number at a time. If there are more numbers than warps in the grid, warps should process multiple numbers in a strided pattern.\n\nThe Miller-Rabin test involves decomposing each number n as n-1 = d * 2^r where d is odd.\nThen for each witness base a, compute a^d mod n and check for composite witnesses through repeated squaring.\n\nExamples:\n```\n>>> k_millerRabin({17, 561, 19, 7919, 23, 1009, 10007, 15}, primalityResults, 8)\n    -> primalityResults({17, 0, 19, 7919, 23, 1009, 10007, 0})\n>>> k_millerRabin({29, 35, 31, 10037, 13, 999331, 7919, 77}, primalityResults, 8)\n    -> primalityResults({29, 0, 31, 10037, 13, 999331, 7919, 0})\n```\n\nNote: The test cases include Carmichael numbers (like 561) that require testing with multiple witnesses to correctly identify as composite."},
 {'role': 'user',
  'content': 'Write a CUDA function using the Thrust library to remove integers from an array if they are divisible by any integer in another array. Use the functor `ThrustTransformFunctor` to do the divisibility checks within the `thrust::transform` function.\n\nThe signature of the functor is:\n```cpp\nstruct ThrustTransformFunctor {\n    __device__ char operator()(TransformInputParameters parameters);\n}\n```\nwhere `TransformInputParameters` is the struct made of parameters for the divisibility checks, and the return value is 1 or 0 depending on the divisibility of selected element.\n\nThe signature of the function is:\n```cpp\nint removeDivisibleElements(thrust::device_vector<int> & dividend_d,\n                            thrust::device_vector<int> & divisor_d,\n                            int numDividends, int numDivisors,\n                            Context & context)\n```\nwhere:\n- `dividend_d` is a reference to the array of dividends in the device\n- `divisor_d` is a reference to the array of divisors in the device\n- `numDividends` is the number of elements in the array of dividends\n- `numDivisors` is the number of elements in the array of divisors\n- `context` is a reference to the thrust::tuple object that contains references to the temporary data used in the removeDivisibleElements function\n- The return value is the number of retained elements in the dividend_d after the removal operation\n\nAll necessary type definitions and the contract are provided in `include/remove_divisible.h`.\n\n**Examples:**\n```\n>>> removeDivisibleElements({ 1000, 1001, 1002, ..., 1049 }, { 10, 11, 12, 13, 14 }, 50, 5, context)\n    -> dividend_d: { 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1011, 1013, 1015, 1016, 1017, 1018, 1019, 1021, 1024, 1025, 1026, 1028, 1029, 1031, 1033, 1035, 1037, 1038, 1039, 1041, 1042, 1043, 1046, 1047, 1048, 1049 }\n\n>>> removeDivisibleElements({ 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114 }, { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 }, 15, 15, context)\n    -> dividend_d: { 101, 103, 107, 109, 113 }\n```'},
 {'role': 'user',
  'content': "Implement a CUDA function to find the kth smallest element in an array of floats using Thrust library's sort functionality.\n\nThe function signature is defined in `include/kth_smallest.h`:\n\n```cpp\nfloat findKthSmallest(thrust::device_vector<float>& data_d, int k,\n                      thrust::device_vector<float>& buffer_d,\n                      cudaStream_t& cudaStream);\n```\n\n**Parameters:**\n- `data_d`: Device vector containing the input data\n- `k`: Position of the element to find (1-based indexing, meaning count starts from 1)\n- `buffer_d`: Device vector used as temporary working storage\n- `cudaStream`: CUDA stream for executing operations asynchronously\n\n**Returns:**\n- The kth smallest element in the array\n\n**Examples:**\n```\nfindKthSmallest({2.0f, 7.0f, 11.0f, 15.0f}, 3, buffer_d, cudaStream) → 11.0f (3rd smallest element)\nfindKthSmallest({3.0f, 2.0f, 4.0f}, 2, buffer_d, cudaStream) → 3.0f (2nd smallest element)\n```\n\nYou may use the `CUDA_CHECK` macro from `include/cuda_helpers.h` for error checking."},
 {'role': 'user',
  'content': 'Write a function to compute the cumulative distribution function (CDF) of grayscale images using the CUDA Thrust library. The pixel values of the image range from 0-255. The function should sort the pixel values, calculate their histogram, derive the CDF, and then map each pixel to its CDF value.\n\nImplement the function with the following signature declared in `include/cdf_calculator.h`:\n\n```cpp\nvoid calculatePixelCdf(thrust::device_vector<int> &srcImage, int size, cudaStream_t stream, thrust::device_vector<float> &output);\n```\n\nWhere:\n- `srcImage` is a reference to the input image matrix of type thrust device_vector<int>\n- `size` is the total number of pixels in the input image\n- `stream` is the CUDA stream for asynchronous execution\n- `output` is a reference to the CDF of each pixel of type thrust device_vector<float>\n\nExample usage:\n```\ncalculatePixelCdf({61, 112, 91, 176, 134, 154, 32, 68, 84, 163, 31, 58, 135, 162, 163, 52}, 16, stream, output)\n→ output: {0.3125, 0.5625, 0.5, 1, 0.625, 0.75, 0.125, 0.375, 0.4375, 0.9375, 0.0625, 0.25, 0.6875, 0.8125, 0.9375, 0.1875}\n\ncalculatePixelCdf({18, 171, 45, 34, 239, 61, 73, 52, 82, 57, 245, 228, 102, 31, 205, 193}, 16, stream, output)\n→ output: {0.0625, 0.6875, 0.25, 0.1875, 0.9375, 0.4375, 0.5, 0.3125, 0.5625, 0.375, 1, 0.875, 0.625, 0.125, 0.8125, 0.75}\n```'},
 {'role': 'user',
  'content': "Use CUB's device-wide primitives to identify all continuous sequences of identical boolean values in a given boolean array, and count the frequency of each sequence.\n\nImplement the function declared in `include/detect_streaks.h`:\n\n```cpp\nvoid detectStreaks(char* input_d, char* streakTypes_d, int* streakLengths_d,\n                   int* numStreaks_d, int inputSize, cudaStream_t stream);\n```\n\n**Parameters:**\n- `input_d`: Device pointer to array of char values (0 or 1)\n- `streakTypes_d`: Device pointer to array of char values indicating the type of each streak (1s or 0s)\n- `streakLengths_d`: Device pointer where the length of each streak will be stored\n- `numStreaks_d`: Device pointer to store the count of streaks found\n- `inputSize`: Size of the input array\n- `stream`: CUDA stream for executing operations asynchronously\n\n**Examples:**\n```\nInput: {1, 1, 0, 0, 0, 1}\nOutput: streakTypes_d = {1, 0, 1}, streakLengths_d = {2, 3, 1}, *numStreaks_d = 3\n\nInput: {0, 0, 1, 1, 1, 0, 0}\nOutput: streakTypes_d = {0, 1, 0}, streakLengths_d = {2, 3, 2}, *numStreaks_d = 3\n```"},
 {'role': 'user',
  'content': 'Implement a function using Thrust that filters out elements from the input array wherever the corresponding value in the predicate array is one.\n\nThe function signature is declared in `include/predicate_filter.h`:\n```cpp\nvoid predicateBasedFilter(thrust::device_vector<int>& inpVector,\n                         thrust::device_vector<int>& predicateVector,\n                         thrust::device_vector<int>& outVector);\n```\n\nwhere `inpVector` is the input vector, `predicateVector` is the vector used to filter input vector (1 means keep the element), and `outVector` is the output filtered vector. All vectors are Thrust device-vectors.\n\nExamples:\n```\npredicateBasedFilter({ 8, 7, -7, -6, 2 }, { 0, 1, 1, 0, 1 }, outVector)\n→ outVector = { 7, -7, 2 }\n\npredicateBasedFilter({ 8, 7, -7, -6, 2, 6, 0, -13, 4, -19 },\n                     { 0, 1, 1, 0, 1, 1, 0, 0, 0, 1 }, outVector)\n→ outVector = { 7, -7, 2, 6, -19 }\n```'},
 {'role': 'user',
  'content': "Use CUB's device-wide primitives to compute inclusive prefix maximum on a device array.\n\nImplement the function declared in `include/prefix_max.h`:\n\n```cpp\nvoid computePrefixMax(int* input_d, int* output_d, int dataSize, cudaStream_t stream);\n```\n\nWhere:\n- `input_d`: pointer to the input array in device memory\n- `output_d`: pointer to the output array in device memory\n- `dataSize`: number of elements to process in the input/output arrays\n- `stream`: CUDA stream for asynchronous execution of the operation\n\nThe function should compute the inclusive prefix maximum using CUB's device-wide scan primitives.\n\n**Examples:**\n```\ncomputePrefixMax({23, 17, 45, 31, 89, 56, 72, 94, 38, 61}, output_d, 10)\n  -> output_d: {23, 23, 45, 45, 89, 89, 89, 94, 94, 94}\n\ncomputePrefixMax({105, 267, 143, 398, 215, 476, 182, 354, 429, 167}, output_d, 10)\n  -> output_d: {105, 267, 267, 398, 398, 476, 476, 476, 476, 476}\n```"},
 {'role': 'user',
  'content': 'Write a CUDA function using CUB device-wide API to transform the input array into its logarithmic form using a given custom functor.\n\nThe function should have the following signature:\n```cpp\nvoid cubNormalizeFunction(int* input_d, float* output_d, int inputSize, cudaStream_t stream);\n```\n\nWhere:\n- `input_d` is the pointer to the input array\n- `output_d` is pointer to the output array where the logarithmic results will be stored\n- `inputSize` is the number of elements in input array\n- `stream` is used for asynchronous operations\n\nThe custom functor `logScalingnormalization` is defined in `include/cub_normalize.h` with:\n```cpp\n__device__ float operator()(int input);\n```\nThis device function computes logarithmic scaling for normalization: log(1 + max(0, input)).\n\nExamples:\n```\n>>> cubNormalizeFunction({85, 27, 49, 75, 63, 97, 0, 92, 17, 38}, output_d, 10, stream)\n    output_d -> {4.454347, 3.332205, 3.912023, 4.330733, 4.158883, 4.584968, 0.000000, 4.532599, 2.890372, 3.663562}\n\n>>> cubNormalizeFunction({24, 96, 20, 64, 11, 52, 88, 43, 35, 28, 2, 59, 90, 78, 8}, output_d, 15, stream)\n    output_d -> {3.218876, 4.574711, 3.044523, 4.174387, 2.484907, 3.970292, 4.488636, 3.784190, 3.583519, 3.367296, 1.098612, 4.094345, 4.510859, 4.369448, 2.197225}\n```'},
 {'role': 'user',
  'content': 'Perform filtering of perfect squares from an integer array using the CUB library with a custom predicate functor which validates the elements, compacting the sequence to retain only qualifying elements and resulting the total count of selected values.\n\nImplement the function declared in `include/perfect_squares.h`:\n\n```cpp\nvoid selectPerfectSquares(int* input_d, int* output_d, int* numSelected_d, int inputSize, cudaStream_t stream);\n```\n\nWhere:\n- `input_d` is a device pointer to the input array\n- `output_d` is a device pointer where the selected perfect squares will be stored\n- `numSelected_d` is a device pointer to store the count of perfect squares found\n- `inputSize` is the size of the input array\n- `stream` is the CUDA stream for executing operations asynchronously\n\nExample behavior:\n- `selectPerfectSquares({1, 4, 9, 3, 7, 16, 25}, output_d, numSelected_d, 7, cudaStream)` → output_d contains {4, 9, 16, 25}, *numSelected_d = 4\n- `selectPerfectSquares({0, 1, 4, 7, 9, 36}, output_d, numSelected_d, 6, cudaStream)` → output_d contains {0, 1, 4, 9, 36}, *numSelected_d = 5'},
 {'role': 'user',
  'content': 'Write a CUDA function that computes histograms for the R, G, and B channels from an RGBA image with equally sized bins using the CUB library.\n\nThe image is stored as an interleaved array of 32-bit pixels, each with four 8-bit unsigned char channels.\n\nImplement the following function in `solution.cu`:\n\n```cpp\nvoid calcMultiHistogram(uint8_t* inputData_d, int** histogram_d,\n                        int* numLevels_h, unsigned int* lowerLevel_h,\n                        unsigned int* upperLevel_h, int numPixels,\n                        cudaStream_t stream);\n```\n\n**Parameters:**\n- `inputData_d`: Pointer to the input sequence of data samples (device memory)\n- `histogram_d`: Pointer to the histogram counter output array (device memory)\n- `numLevels_h`: Pointer to array containing number of boundaries for histogram samples (host memory)\n- `lowerLevel_h`: Pointer to the array containing lower sample value bound for the lowest histogram bin (host memory)\n- `upperLevel_h`: Pointer to the array containing upper sample value bound for the highest histogram bin (host memory)\n- `numPixels`: Number of pixels in input image\n- `stream`: Handle for asynchronous operations\n\nYour solution should use `cub::DeviceHistogram::MultiHistogramEven` to compute the histograms.\n\n**Example:**\n```\nInput: {{2, 6, 7, 5}, {3, 0, 2, 1}, {7, 0, 6, 2}, {0, 6, 7, 5}, {3, 0, 2, 6}}\n       numLevels={5, 5, 5}, lowerLevel={0, 0, 0}, upperLevel={256, 256, 256}\nOutput: histogram_d[0] = {5, 0, 0, 0}  (R channel)\n        histogram_d[1] = {5, 0, 0, 0}  (G channel)\n        histogram_d[2] = {5, 0, 0, 0}  (B channel)\n```\n\nInclude the contract header `histogram.h` and the helpers header `histogram_helpers.h` from the `include/` directory.'},
 {'role': 'user',
  'content': "Use CUB's device-wide primitives to compute the minimum and maximum values of each segment of a row major matrix of dimension m x n. Consider each row as an individual segment.\n\nImplement the function declared in `include/minmax_function.h`:\n\n```cpp\nvoid minMaxFunction(int* input_d, int* outputMin_d, int* outputMax_d, int rows, int cols, cudaStream_t stream);\n```\n\nwhere:\n- `input_d` is the input matrix data (row-major order)\n- `outputMin_d` stores the minimum value of each row\n- `outputMax_d` stores the maximum value of each row\n- `rows` specifies the number of rows in the matrix (number of segments)\n- `cols` represents the number of columns in the matrix\n- `stream` is used for asynchronous operations\n\n**Examples:**\n```\nminMaxFunction({{10, 6, 8}, {9, 5, 12}}, outputMin_d, outputMax_d, 2, 3, stream)\n→ outputMin_d = {6, 5}, outputMax_d = {10, 12}\n\nminMaxFunction({{18, 16, 14, 15}, {19, 21, 20, 17}, {22, 24, 28, 23}}, outputMin_d, outputMax_d, 3, 4, stream)\n→ outputMin_d = {14, 17, 22}, outputMax_d = {18, 21, 28}\n```\n\nYou may use the helper macros defined in `include/cuda_helpers.h`."},
 {'role': 'user',
  'content': 'Use the Thrust API to perform a parallel element-wise transformation on the array with a custom predicate that uses a flag array to mark peaks (elements greater than both neighbors) with 1 and valleys (elements smaller than both neighbors) with -1.\n\nImplement the function declared in `include/peaks_valleys.h`:\n```cpp\nvoid detectPeaksAndValleys(thrust::device_vector<int>& data_d,\n                          thrust::device_vector<int>& flags_d,\n                          cudaStream_t& cudaStream);\n```\n\nWhere:\n- `data_d` is a device vector containing the input data points\n- `flags_d` is an output device vector that will be populated with flags indicating peaks (1), valleys (-1), or neither (0) for each corresponding position in data_d\n- `cudaStream` is the CUDA stream for executing operations asynchronously\n\nYou should also define a functor:\n```cpp\nstruct d_PeakValleyFunctor {\n    __device__ int operator()(int idx) const;\n};\n```\n\nWhere:\n- `idx` is the index of the element to check in the data array\n- The return value is 1 for peaks, -1 for valleys, or 0 for neither\n\nExamples:\n```\ndetectPeaksAndValleys([5,2,6,2,7,3], flags_d, cudaStream) -> flags_d = [0,-1,1,-1,1,0]\n  (valleys at positions 1 and 3, peaks at positions 2 and 4)\n\ndetectPeaksAndValleys([1,2,3,4,5], flags_d, cudaStream) -> flags_d = [0,0,0,0,0]\n  (no peaks or valleys in a monotonically increasing sequence)\n```'},
 {'role': 'user',

In [4]:
from transformers import pipeline
import torch

model_id = "openai/gpt-oss-20b"

pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype="auto",
    device_map="auto",
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
MXFP4 quantization requires Triton and kernels installed: CUDA requires Triton >= 3.4.0, XPU requires Triton >= 3.5.0, we will default to dequantizing the model to bf16

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/411 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/177 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/98.0 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

In [ ]:
idx = 0
for concat_prompts in concat_prompt_list:
  outputs = pipe(
      concat_prompts_firstpart,
      max_new_tokens=256,
  )

In [27]:
concat_prompts_firstpart[:2]

[{'role': 'user',
  'content': 'Develop a CUDA program using the Thrust API to search for a set of elements within an input array and return their corresponding indices. If multiple occurrences of an element exist in the input array, the index of its first occurrence will be returned; if an element is not found, -1 will be returned.\n\nYour implementation must be in `solution.cu` and use the contract defined in `include/find_indices.h`.\n\n**Function Signature:**\n```cpp\nthrust::device_vector<int> findIndices(const thrust::device_vector<int>& inputArray_d,\n                                       const thrust::device_vector<int>& testData_d);\n```\n\n**Parameters:**\n- `inputArray_d`: The source/input array (unsorted)\n- `testData_d`: Elements to search for in inputArray_d\n\n**Returns:**\n- A device vector containing the index of each testData_d element in inputArray_d if found, -1 otherwise\n\n**Functor (defined in header):**\n- `struct indexUpdate`: Contains a device operator that updates the result vector with -1 for elements not found\n- `__device__ void operator()(int i)`: Where `i` is the index of the test data element being checked\n\n**Examples:**\n```cpp\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {2, 3, 81, 46})\n// Output: {2, 40, 16, -1}\n\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {34, 87, 12, 59, 3, 76, 41, 68, 25, 93})\n// Output: {28, -1, 48, 39, 40, 14, -1, 30, -1, 4}\n```'},
 {'role': 'user',
  'content': "Write a CUDA kernel to test the primality of a list of numbers using the Miller-Rabin algorithm.\nThe kernel should be launched with different configurations of blocksize.\n\nYour implementation must be in `solution.cu` and include `miller_rabin.h`. Implement the following kernel signature:\n\n```cuda\n__global__ void k_millerRabin(unsigned long long *inputNumbers, unsigned long long *primalityResults, int numberOfElements);\n```\n\nWhere:\n- `inputNumbers`: array of input numbers to be tested for primality\n- `primalityResults`: pointer to the array where the primality test results will be stored (the number is stored if prime, else 0 if composite)\n- `numberOfElements`: total number of inputNumbers\n\n**Parallelization Requirements:**\n\nThe kernel must use warp-level cooperative parallelism where each warp collectively tests a single number.\nWithin each warp, different threads must test the same number against different witnesses (base values) in parallel.\nEach thread should select its witness based on its position within the warp, starting from base 2 and incrementing for each subsequent thread.\nAll threads in a warp must agree on primality for the number to be considered prime.\n\nThe kernel should use dynamic shared memory for coordination within each block.\nYou'll need to store intermediate Miller-Rabin decomposition values that can be shared across threads in the same warp.\nThe helper function `dynamicSMemSizeMillerRabin` computes the required shared memory size.\n\nEach warp processes one number at a time. If there are more numbers than warps in the grid, warps should process multiple numbers in a strided pattern.\n\nThe Miller-Rabin test involves decomposing each number n as n-1 = d * 2^r where d is odd.\nThen for each witness base a, compute a^d mod n and check for composite witnesses through repeated squaring.\n\nExamples:\n```\n>>> k_millerRabin({17, 561, 19, 7919, 23, 1009, 10007, 15}, primalityResults, 8)\n    -> primalityResults({17, 0, 19, 7919, 23, 1009, 10007, 0})\n>>> k_millerRabin({29, 35, 31, 10037, 13, 999331, 7919, 77}, primalityResults, 8)\n    -> primalityResults({29, 0, 31, 10037, 13, 999331, 7919, 0})\n```\n\nNote: The test cases include Carmichael numbers (like 561) that require testing with multiple witnesses to correctly identify as composite."}]

In [30]:
message = [{'role': 'user', 'content':'who are you?'}]
outputs = pipe(
      concat_prompts_firstpart[:2]
  )

Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [31]:
outputs

[{'generated_text': [{'role': 'user',
    'content': 'Develop a CUDA program using the Thrust API to search for a set of elements within an input array and return their corresponding indices. If multiple occurrences of an element exist in the input array, the index of its first occurrence will be returned; if an element is not found, -1 will be returned.\n\nYour implementation must be in `solution.cu` and use the contract defined in `include/find_indices.h`.\n\n**Function Signature:**\n```cpp\nthrust::device_vector<int> findIndices(const thrust::device_vector<int>& inputArray_d,\n                                       const thrust::device_vector<int>& testData_d);\n```\n\n**Parameters:**\n- `inputArray_d`: The source/input array (unsorted)\n- `testData_d`: Elements to search for in inputArray_d\n\n**Returns:**\n- A device vector containing the index of each testData_d element in inputArray_d if found, -1 otherwise\n\n**Functor (defined in header):**\n- `struct indexUpdate`: Contains a device operator that updates the result vector with -1 for elements not found\n- `__device__ void operator()(int i)`: Where `i` is the index of the test data element being checked\n\n**Examples:**\n```cpp\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {2, 3, 81, 46})\n// Output: {2, 40, 16, -1}\n\nfindIndices({37, 85, 2, 15, 93, 47, 70, 64, 99, 28, 55, 23, 40, 11, 76, 36, 81, 13, 32, 50, 7, 26, 71, 62, 19, 88, 4, 43, 34, 91, 68, 60, 24, 96, 38, 9, 21, 45, 78, 59, 3, 67, 6, 20, 49, 84, 27, 29, 12, 31},\n            {34, 87, 12, 59, 3, 76, 41, 68, 25, 93})\n// Output: {28, -1, 48, 39, 40, 14, -1, 30, -1, 4}\n```'},
   {'role': 'user',
    'content': "Write a CUDA kernel to test the primality of a list of numbers using the Miller-Rabin algorithm.\nThe kernel should be launched with different configurations of blocksize.\n\nYour implementation must be in `solution.cu` and include `miller_rabin.h`. Implement the following kernel signature:\n\n```cuda\n__global__ void k_millerRabin(unsigned long long *inputNumbers, unsigned long long *primalityResults, int numberOfElements);\n```\n\nWhere:\n- `inputNumbers`: array of input numbers to be tested for primality\n- `primalityResults`: pointer to the array where the primality test results will be stored (the number is stored if prime, else 0 if composite)\n- `numberOfElements`: total number of inputNumbers\n\n**Parallelization Requirements:**\n\nThe kernel must use warp-level cooperative parallelism where each warp collectively tests a single number.\nWithin each warp, different threads must test the same number against different witnesses (base values) in parallel.\nEach thread should select its witness based on its position within the warp, starting from base 2 and incrementing for each subsequent thread.\nAll threads in a warp must agree on primality for the number to be considered prime.\n\nThe kernel should use dynamic shared memory for coordination within each block.\nYou'll need to store intermediate Miller-Rabin decomposition values that can be shared across threads in the same warp.\nThe helper function `dynamicSMemSizeMillerRabin` computes the required shared memory size.\n\nEach warp processes one number at a time. If there are more numbers than warps in the grid, warps should process multiple numbers in a strided pattern.\n\nThe Miller-Rabin test involves decomposing each number n as n-1 = d * 2^r where d is odd.\nThen for each witness base a, compute a^d mod n and check for composite witnesses through repeated squaring.\n\nExamples:\n```\n>>> k_millerRabin({17, 561, 19, 7919, 23, 1009, 10007, 15}, primalityResults, 8)\n    -> primalityResults({17, 0, 19, 7919, 23, 1009, 10007, 0})\n>>> k_millerRabin({29, 35, 31, 10037, 13, 999331, 7919, 77}, primalityResults, 8)\n    -> primalityResults({29, 0, 31, 10037, 13, 999331, 7919, 0})\n```\n\nNote: The test cases include Carmichael numbers (like 561) that require testing with multiple witnesses to correctly identify as composite."},
   {'role': 'assistant',
    'content': 'analysisWe have two tasks: first one about findIndices using Thrust. second about Miller-Rabin kernel. But the user says: "Write a CUDA kernel to test the primality of a list of numbers using the Miller-Rabin algorithm." They want implementation in solution.cu including miller_rabin.h. So likely they want only the Miller-Rabin part. But earlier they also described findIndices. But the last instruction: "Your implementation must be in solution.cu and include miller_rabin.h. Implement the following kernel signature:...". So they want just Miller-Rabin kernel.\n\nThus we need to provide a solution.cu file with kernel k_millerRabin, possibly using helper functions, dynamic shared memory, warp-level cooperation.\n\nWe need to consider the header miller_rabin.h: It likely defines certain constants, helper functions like powmod, etc. We need to assume some functions exist: maybe dynamicSMemSizeMillerRabin, modPow, etc. We need to design kernel accordingly.\n\nLet\'s design:\n\n- Each warp tests one number. So threadIdx.x within block gives thread number. warpSize = 32. So thread\'s lane = threadIdx.x % warpSize. warpID = (blockIdx.x *'}]}]

### vLLM
vLLM is a fast and efficient inference engine for large language models. It is designed to achieve high throughput and low latency.

In [8]:
!pip install uv

Collecting uv
  Downloading uv-0.11.8-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.11.8-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 89.1 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.11.8

In [ ]:
# Install vLLM
!uv pip install vllm --torch-backend=auto

In [10]:
def invoke_vllm() -> dict:
  from vllm import LLM, SamplingParams
  import sys
  import os

  prompts = [
      "Hello, my name is",
      "The president of the United States is",
      "The capital of France is",
      "The future of AI is",
  ]
  sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

  # Temporarily redirect stdout and stderr to /dev/null
  # This is a workaround for vLLM's internal suppress_stdout
  # which calls fileno() on sys.stdout/sys.stderr, which is not
  # supported in some interactive environments like Colab.
  original_stdout = sys.stdout
  original_stderr = sys.stderr
  sys.stdout = open(os.devnull, 'w')
  sys.stderr = open(os.devnull, 'w')

  try:
    llm = LLM(model="deepseek-ai/deepseek-llm-7b-base")
  finally:
    # Restore original stdout and stderr
    sys.stdout.close()
    sys.stderr.close()
    sys.stdout = original_stdout
    sys.stderr = original_stderr

  outputs = llm.generate(prompts, sampling_params)
  return outputs

### Model Distribution

- cuda: 0
  - combined size of model weights, gradients, optimizer states and intermediate activations
  - Exception: CUDA Out of memory


> deepseek-llm-67b-base \
> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 344.00 MiB. GPU 0 has a total capacity of 79.25 GiB of which 40.81 MiB is free.


- Distributing larger model:
  - Data Parallelism
  - Model Parallelism

In [11]:
outputs = invoke_vllm()

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

ImportError: cannot import name 'XPU_KERNEL_FORMAT' from 'torch._inductor.utils' (/usr/local/lib/python3.12/dist-packages/torch/_inductor/utils.py)

# Customized Evaluator

## Numeric Metrics Evaluation
### metrics:
- accuracy (pass rate)
- performance (latency v.s. time out value)

In [53]:
def evaluator(task_id: str, generated_cuda_code:str, solution_cuda_code:str, context_files:list, test_files:list, build_command:str, test_command:str) -> dict:
  task_id = task_id.replace('CUDA/', '')
  with tempfile.TemporaryDirectory() as tmpdir:
    solution_file_path = os.path.join(tmpdir, 'solution.cu')
    executable_path = os.path.join(tmpdir, 'test.out') # Using the build command's expected output name

    # Write context files to the temporary directory
    for file_info in context_files:
        file_path = os.path.join(tmpdir, file_info['path'])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, 'w') as f:
            f.write(file_info['content'])
        print(f"Context file '{file_path}' created.")

    # Write test files to the temporary directory test/test_main.cu
    for file_info in test_files:
        file_path = os.path.join(tmpdir, file_info['path'])
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, 'w') as f:
            f.write(file_info['content'])
        print(f"Test file '{file_path}' created.")

    # Write the solution.cu file
    with open(solution_file_path, 'w') as f:
        f.write(generated_cuda_code)
    print(f"Solution file '{solution_file_path}' created.")

    # 3. Compile the CUDA code using nvcc
    # Using the build command from the dataset for consistency
    build_command = build_command.replace('solution.cu', solution_file_path).replace('./test.out', executable_path)
    print(f"Compile with '{build_command}'.")
    compile_result = subprocess.run(build_command, shell=True, cwd=tmpdir, capture_output=True, text=True)

    if compile_result.returncode == 0:
        # 4. Run the compiled CUDA executable
        # Using the test command from the dataset
        test_command = test_command.replace('./test.out', executable_path) # Adjust path if necessary
        print(f"Test with '{test_command}'.")
        run_result = subprocess.run(test_command, shell=True, cwd=tmpdir, capture_output=True, text=True)
        print("[Task_" + task_id + "] Execution Result: Success" + str(run_result.returncode))
        return {
              'status': True,
              'task_id': task_id,
              'reason': 'Test Passed'
        }

        if run_result.returncode != 0:
          print("[Task_" + task_id + "] Execution Result: Fail" + str(run_result.returncode))
          return {
            'status': False,
            'task_id': task_id,
            'reason': 'Executable run failed',
            'error_message': 'stdout ==> ' + compile_result.stdout + " stderr ==> " + compile_result.stderr
            }
    else:
      print("[Task_" + task_id + "] Compilation Failed")
      return {
          'status': False,
          'task_id': task_id,
          'reason': 'Compilation failed',
          'error_message': 'stdout ==> ' + compile_result.stdout + " stderr ==> " + compile_result.stderr
      }

In [ ]:
pass_count = 0;
total_count = 2
evaluation_results = []

for index, input_row in df.iterrows():
  problem_row =input_row
  result = evaluator(input_row['task_id'], input_row['baseline_solution']['files'][0]['content'], '', input_row['context_files'], input_row['test_files'], input_row['build_command'], input_row['test_command'])
  print("RESULT: " + result['task_id'] + '==>' + str(result['status']))
  evaluation_results.append(result)
  if result['status']:
    pass_count+=1

evaluation_df = pd.DataFrame(evaluation_results)
print("\nEvaluation Summary:")
print(evaluation_df)
print('Accumulated accuracy ==>' + str(pass_count/total_count * 100) + '%')

Context file '/tmp/tmpq9evtvuj/include/find_indices.h' created.
Test file '/tmp/tmpq9evtvuj/test/test_main.cu' created.
Solution file '/tmp/tmpq9evtvuj/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpq9evtvuj/solution.cu test/*.cu'.
Test with '/tmp/tmpq9evtvuj/test.out'.
[Task_146] Execution Result: Success0
RESULT: 146==>True
Context file '/tmp/tmpd2922fpm/helper.cu' created.
Context file '/tmp/tmpd2922fpm/include/miller_rabin.h' created.
Test file '/tmp/tmpd2922fpm/test/test_main.cu' created.
Solution file '/tmp/tmpd2922fpm/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpd2922fpm/solution.cu helper.cu test/*.cu'.
Test with '/tmp/tmpd2922fpm/test.out'.
[Task_151] Execution Result: Success0
RESULT: 151==>True
Context file '/tmp/tmpou8g1uk9/include/remove_divisible.h' created.
Test file '/tmp/tmpou8g1uk9/test/test_main.cu' created.
Solution file '/tmp/tmpou8g1uk9/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpou8g1uk9/solution.cu test/*.cu'.
Test with '/tmp/tmpou8g1uk9/test.out'.
[Task_152] Execution Result: Success0
RESULT: 152==>True
Context file '/tmp/tmpnqsfritr/include/kth_smallest.h' created.
Context file '/tmp/tmpnqsfritr/include/cuda_helpers.h' created.
Test file '/tmp/tmpnqsfritr/test/test_main.cu' created.
Solution file '/tmp/tmpnqsfritr/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpnqsfritr/solution.cu test/*.cu'.
Test with '/tmp/tmpnqsfritr/test.out'.
[Task_156] Execution Result: Success0
RESULT: 156==>True
Context file '/tmp/tmpdxzt3f1s/include/cdf_calculator.h' created.
Context file '/tmp/tmpdxzt3f1s/include/cuda_utils.h' created.
Test file '/tmp/tmpdxzt3f1s/test/test_main.cu' created.
Solution file '/tmp/tmpdxzt3f1s/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpdxzt3f1s/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpdxzt3f1s/test.out'.
[Task_157] Execution Result: Success0
RESULT: 157==>True
Context file '/tmp/tmp0vgocxbq/include/detect_streaks.h' created.
Test file '/tmp/tmp0vgocxbq/test/test_main.cu' created.
Solution file '/tmp/tmp0vgocxbq/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp0vgocxbq/solution.cu test/*.cu'.
Test with '/tmp/tmp0vgocxbq/test.out'.
[Task_160] Execution Result: Success0
RESULT: 160==>True
Context file '/tmp/tmp58gobp0m/include/predicate_filter.h' created.
Test file '/tmp/tmp58gobp0m/test/test_main.cu' created.
Solution file '/tmp/tmp58gobp0m/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp58gobp0m/solution.cu test/*.cu'.
Test with '/tmp/tmp58gobp0m/test.out'.
[Task_164] Execution Result: Success0
RESULT: 164==>True
Context file '/tmp/tmp85_njadi/include/prefix_max.h' created.
Context file '/tmp/tmp85_njadi/include/cuda_utils.h' created.
Test file '/tmp/tmp85_njadi/test/test_main.cu' created.
Solution file '/tmp/tmp85_njadi/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp85_njadi/solution.cu test/*.cu  -ldl'.
Test with '/tmp/tmp85_njadi/test.out'.
[Task_170] Execution Result: Success0
RESULT: 170==>True
Context file '/tmp/tmp9rvcs3ou/include/cuda_helpers.h' created.
Context file '/tmp/tmp9rvcs3ou/include/cub_normalize.h' created.
Test file '/tmp/tmp9rvcs3ou/test/test_main.cu' created.
Solution file '/tmp/tmp9rvcs3ou/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp9rvcs3ou/solution.cu test/*.cu -Icccl/thrust -Icccl/libcudacxx/include -Icccl/cub --extended-lambda'.
[Task_175] Compilation Failed
RESULT: 175==>False
Context file '/tmp/tmp9jip39xh/include/perfect_squares.h' created.
Context file '/tmp/tmp9jip39xh/include/cuda_utils.h' created.
Test file '/tmp/tmp9jip39xh/test/test_main.cu' created.
Solution file '/tmp/tmp9jip39xh/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp9jip39xh/solution.cu test/*.cu'.
Test with '/tmp/tmp9jip39xh/test.out'.
[Task_176] Execution Result: Success0
RESULT: 176==>True
Context file '/tmp/tmpcxaey_p8/include/histogram_helpers.h' created.
Context file '/tmp/tmpcxaey_p8/include/histogram.h' created.
Test file '/tmp/tmpcxaey_p8/test/test_main.cu' created.
Solution file '/tmp/tmpcxaey_p8/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpcxaey_p8/solution.cu test/*.cu'.
Test with '/tmp/tmpcxaey_p8/test.out'.
[Task_177] Execution Result: Success0
RESULT: 177==>True
Context file '/tmp/tmp5nkpd1xf/include/minmax_function.h' created.
Context file '/tmp/tmp5nkpd1xf/include/cuda_helpers.h' created.
Test file '/tmp/tmp5nkpd1xf/test/test_main.cu' created.
Solution file '/tmp/tmp5nkpd1xf/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp5nkpd1xf/solution.cu test/*.cu'.
Test with '/tmp/tmp5nkpd1xf/test.out'.
[Task_178] Execution Result: Success0
RESULT: 178==>True
Context file '/tmp/tmpu1rjpfzs/include/peaks_valleys.h' created.
Context file '/tmp/tmpu1rjpfzs/include/cuda_utils.h' created.
Test file '/tmp/tmpu1rjpfzs/test/test_main.cu' created.
Solution file '/tmp/tmpu1rjpfzs/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpu1rjpfzs/solution.cu test/*.cu'.
Test with '/tmp/tmpu1rjpfzs/test.out'.
[Task_179] Execution Result: Success0
RESULT: 179==>True
Context file '/tmp/tmpb2_3rmaa/include/mode_detection.h' created.
Test file '/tmp/tmpb2_3rmaa/test/test_main.cu' created.
Solution file '/tmp/tmpb2_3rmaa/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpb2_3rmaa/solution.cu test/*.cu'.
[Task_181] Compilation Failed
RESULT: 181==>False
Context file '/tmp/tmpos_1zq5d/include/minkowski.h' created.
Test file '/tmp/tmpos_1zq5d/test/test_main.cu' created.
Solution file '/tmp/tmpos_1zq5d/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpos_1zq5d/solution.cu test/*.cu'.
Test with '/tmp/tmpos_1zq5d/test.out'.
[Task_182] Execution Result: Success0
RESULT: 182==>True
Context file '/tmp/tmp1rc9qypn/include/complex_powers.h' created.
Test file '/tmp/tmp1rc9qypn/test/test_main.cu' created.
Solution file '/tmp/tmp1rc9qypn/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp1rc9qypn/solution.cu test/*.cu'.
Test with '/tmp/tmp1rc9qypn/test.out'.
[Task_187] Execution Result: Success0
RESULT: 187==>True
Context file '/tmp/tmp9abqu5l2/include/saxpy_thrust.h' created.
Test file '/tmp/tmp9abqu5l2/test/test_main.cu' created.
Solution file '/tmp/tmp9abqu5l2/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp9abqu5l2/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmp9abqu5l2/test.out'.
[Task_188] Execution Result: Success0
RESULT: 188==>True
Context file '/tmp/tmpyeyzhvq9/include/rotation_index.h' created.
Test file '/tmp/tmpyeyzhvq9/test/test_main.cu' created.
Solution file '/tmp/tmpyeyzhvq9/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpyeyzhvq9/solution.cu test/*.cu'.
Test with '/tmp/tmpyeyzhvq9/test.out'.
[Task_192] Execution Result: Success0
RESULT: 192==>True
Context file '/tmp/tmp3ctun8dv/include/blur_kernel.h' created.
Test file '/tmp/tmp3ctun8dv/test/test_main.cu' created.
Solution file '/tmp/tmp3ctun8dv/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp3ctun8dv/solution.cu test/*.cu'.
Test with '/tmp/tmp3ctun8dv/test.out'.
[Task_196] Execution Result: Success0
RESULT: 196==>True
Context file '/tmp/tmpwisqrj__/include/cuda_helpers.h' created.
Context file '/tmp/tmpwisqrj__/include/sort_segments.h' created.
Test file '/tmp/tmpwisqrj__/test/test_main.cu' created.
Solution file '/tmp/tmpwisqrj__/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwisqrj__/solution.cu test/*.cu'.
Test with '/tmp/tmpwisqrj__/test.out'.
[Task_205] Execution Result: Success0
RESULT: 205==>True
Test file '/tmp/tmpdpo8upi6/test/test_main.cu' created.
Solution file '/tmp/tmpdpo8upi6/solution.cu' created.
Compile with 'nvcc -I . -o test.out /tmp/tmpdpo8upi6/solution.cu test/*.cu -std=c++17'.
Test with '/tmp/tmpdpo8upi6/test.out'.
[Task_228] Execution Result: Success0
RESULT: 228==>True
Context file '/tmp/tmpwxs40n67/include/add.h' created.
Test file '/tmp/tmpwxs40n67/test/test_main.cu' created.
Solution file '/tmp/tmpwxs40n67/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwxs40n67/solution.cu test/*.cu'.
Test with '/tmp/tmpwxs40n67/test.out'.
[Task_31] Execution Result: Success0
RESULT: 31==>True
Context file '/tmp/tmpwrbjgjov/include/scan.h' created.
Test file '/tmp/tmpwrbjgjov/test/test_main.cu' created.
Solution file '/tmp/tmpwrbjgjov/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwrbjgjov/solution.cu test/*.cu'.
Test with '/tmp/tmpwrbjgjov/test.out'.
[Task_32] Execution Result: Success0
RESULT: 32==>True
Context file '/tmp/tmpwxbm_n3z/include/sort.h' created.
Test file '/tmp/tmpwxbm_n3z/test/test_main.cu' created.
Solution file '/tmp/tmpwxbm_n3z/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwxbm_n3z/solution.cu test/*.cu'.
Test with '/tmp/tmpwxbm_n3z/test.out'.
[Task_33] Execution Result: Success0
RESULT: 33==>True
Context file '/tmp/tmpmuan8clx/include/kernel.h' created.
Test file '/tmp/tmpmuan8clx/test/test_main.cu' created.
Solution file '/tmp/tmpmuan8clx/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpmuan8clx/solution.cu test/*.cu  --extended-lambda'.
[Task_34] Compilation Failed
RESULT: 34==>False
Context file '/tmp/tmpgs43pp_s/include/scan.h' created.
Test file '/tmp/tmpgs43pp_s/test/test_main.cu' created.
Solution file '/tmp/tmpgs43pp_s/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpgs43pp_s/solution.cu test/*.cu'.
Test with '/tmp/tmpgs43pp_s/test.out'.
[Task_35] Execution Result: Success0
RESULT: 35==>True
Context file '/tmp/tmpmffhtox6/include/thrust_sum.h' created.
Test file '/tmp/tmpmffhtox6/test/test_main.cu' created.
Solution file '/tmp/tmpmffhtox6/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpmffhtox6/solution.cu test/*.cu'.
Test with '/tmp/tmpmffhtox6/test.out'.
[Task_36] Execution Result: Success0
RESULT: 36==>True
Context file '/tmp/tmp6oo8_1so/include/sort.h' created.
Test file '/tmp/tmp6oo8_1so/test/test_main.cu' created.
Solution file '/tmp/tmp6oo8_1so/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp6oo8_1so/solution.cu test/*.cu'.
Test with '/tmp/tmp6oo8_1so/test.out'.
[Task_37] Execution Result: Success0
RESULT: 37==>True
Context file '/tmp/tmpjqk9yj4v/include/vadd.h' created.
Test file '/tmp/tmpjqk9yj4v/test/test_main.cu' created.
Solution file '/tmp/tmpjqk9yj4v/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpjqk9yj4v/solution.cu test/*.cu'.
Test with '/tmp/tmpjqk9yj4v/test.out'.
[Task_38] Execution Result: Success0
RESULT: 38==>True
Context file '/tmp/tmpfs6uk0ai/include/find.h' created.
Test file '/tmp/tmpfs6uk0ai/test/test_main.cu' created.
Solution file '/tmp/tmpfs6uk0ai/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpfs6uk0ai/solution.cu test/*.cu'.
Test with '/tmp/tmpfs6uk0ai/test.out'.
[Task_39] Execution Result: Success0
RESULT: 39==>True
Context file '/tmp/tmpcgdvfltl/include/inclusive_add.h' created.
Test file '/tmp/tmpcgdvfltl/test/test_main.cu' created.
Solution file '/tmp/tmpcgdvfltl/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpcgdvfltl/solution.cu test/*.cu'.
Test with '/tmp/tmpcgdvfltl/test.out'.
[Task_40] Execution Result: Success0
RESULT: 40==>True
Context file '/tmp/tmp248hj96h/include/partition_vector.h' created.
Test file '/tmp/tmp248hj96h/test/test_main.cu' created.
Solution file '/tmp/tmp248hj96h/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp248hj96h/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmp248hj96h/test.out'.
[Task_41] Execution Result: Success0
RESULT: 41==>True
Context file '/tmp/tmpqmyrgut0/include/partition_vector.h' created.
Test file '/tmp/tmpqmyrgut0/test/test_main.cu' created.
Solution file '/tmp/tmpqmyrgut0/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpqmyrgut0/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpqmyrgut0/test.out'.
[Task_42] Execution Result: Success0
RESULT: 42==>True
Context file '/tmp/tmp35c9vqzj/include/copy_half.h' created.
Test file '/tmp/tmp35c9vqzj/test/test_main.cu' created.
Solution file '/tmp/tmp35c9vqzj/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp35c9vqzj/solution.cu test/*.cu'.
Test with '/tmp/tmp35c9vqzj/test.out'.
[Task_43] Execution Result: Success0
RESULT: 43==>True
Context file '/tmp/tmpwt3ajzuc/include/fill_vector.h' created.
Test file '/tmp/tmpwt3ajzuc/test/test_main.cu' created.
Solution file '/tmp/tmpwt3ajzuc/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwt3ajzuc/solution.cu test/*.cu  -ldl'.
Test with '/tmp/tmpwt3ajzuc/test.out'.
[Task_44] Execution Result: Success0
RESULT: 44==>True
Context file '/tmp/tmp9f3z74_a/include/combine_ranges.h' created.
Test file '/tmp/tmp9f3z74_a/test/test_main.cu' created.
Solution file '/tmp/tmp9f3z74_a/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp9f3z74_a/solution.cu test/*.cu'.
Test with '/tmp/tmp9f3z74_a/test.out'.
[Task_45] Execution Result: Success0
RESULT: 45==>True
Context file '/tmp/tmpwhml2kp1/include/square.h' created.
Test file '/tmp/tmpwhml2kp1/test/test_main.cu' created.
Solution file '/tmp/tmpwhml2kp1/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpwhml2kp1/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpwhml2kp1/test.out'.
[Task_46] Execution Result: Success0
RESULT: 46==>True
Context file '/tmp/tmp2qis996d/include/redistribute.h' created.
Test file '/tmp/tmp2qis996d/test/test_main.cu' created.
Solution file '/tmp/tmp2qis996d/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp2qis996d/solution.cu test/*.cu'.
Test with '/tmp/tmp2qis996d/test.out'.
[Task_47] Execution Result: Success0
RESULT: 47==>True
Context file '/tmp/tmpb6rfr4c2/include/remap_elements.h' created.
Test file '/tmp/tmpb6rfr4c2/test/test_main.cu' created.
Solution file '/tmp/tmpb6rfr4c2/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpb6rfr4c2/solution.cu test/*.cu  --extended-lambda'.
Test with '/tmp/tmpb6rfr4c2/test.out'.
[Task_48] Execution Result: Success0
RESULT: 48==>True
Context file '/tmp/tmp4aa3mf25/include/partition_finder.h' created.
Test file '/tmp/tmp4aa3mf25/test/test_main.cu' created.
Solution file '/tmp/tmp4aa3mf25/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp4aa3mf25/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmp4aa3mf25/test.out'.
[Task_49] Execution Result: Success0
RESULT: 49==>True
Context file '/tmp/tmpvi7a4slp/include/shift_iterator.h' created.
Test file '/tmp/tmpvi7a4slp/test/test_main.cu' created.
Solution file '/tmp/tmpvi7a4slp/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpvi7a4slp/solution.cu test/*.cu'.
Test with '/tmp/tmpvi7a4slp/test.out'.
[Task_50] Execution Result: Success0
RESULT: 50==>True
Context file '/tmp/tmp6z0nc3xy/include/flip_values.h' created.
Test file '/tmp/tmp6z0nc3xy/test/test_main.cu' created.
Solution file '/tmp/tmp6z0nc3xy/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp6z0nc3xy/solution.cu test/*.cu'.
Test with '/tmp/tmp6z0nc3xy/test.out'.
[Task_51] Execution Result: Success0
RESULT: 51==>True
Context file '/tmp/tmpxhryq2xx/include/find_word.h' created.
Test file '/tmp/tmpxhryq2xx/test/test_main.cu' created.
Solution file '/tmp/tmpxhryq2xx/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpxhryq2xx/solution.cu test/test_main.cu -ldl'.
Test with '/tmp/tmpxhryq2xx/test.out'.
[Task_52] Execution Result: Success0
RESULT: 52==>True
Context file '/tmp/tmptqlp0kk0/include/local_prefix_maxima.h' created.
Test file '/tmp/tmptqlp0kk0/test/test_main.cu' created.
Solution file '/tmp/tmptqlp0kk0/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmptqlp0kk0/solution.cu test/*.cu  --extended-lambda'.
Test with '/tmp/tmptqlp0kk0/test.out'.
[Task_53] Execution Result: Success0
RESULT: 53==>True
Context file '/tmp/tmp04pm2ju6/include/remove_duplicates.h' created.
Test file '/tmp/tmp04pm2ju6/test/test_main.cu' created.
Solution file '/tmp/tmp04pm2ju6/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp04pm2ju6/solution.cu test/*.cu'.
Test with '/tmp/tmp04pm2ju6/test.out'.
[Task_54] Execution Result: Success0
RESULT: 54==>True
Context file '/tmp/tmpm3lizkww/include/local_prefix_sum.h' created.
Test file '/tmp/tmpm3lizkww/test/test_main.cu' created.
Solution file '/tmp/tmpm3lizkww/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpm3lizkww/solution.cu test/*.cu  -ldl'.
Test with '/tmp/tmpm3lizkww/test.out'.
[Task_55] Execution Result: Success0
RESULT: 55==>True
Context file '/tmp/tmpgfoj9d7i/include/negate_and_add.h' created.
Test file '/tmp/tmpgfoj9d7i/test/test_main.cu' created.
Solution file '/tmp/tmpgfoj9d7i/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpgfoj9d7i/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpgfoj9d7i/test.out'.
[Task_56] Execution Result: Success0
RESULT: 56==>True
Context file '/tmp/tmp4fs700m7/include/replace_twos.h' created.
Test file '/tmp/tmp4fs700m7/test/test_main.cu' created.
Solution file '/tmp/tmp4fs700m7/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp4fs700m7/solution.cu test/*.cu'.
Test with '/tmp/tmp4fs700m7/test.out'.
[Task_57] Execution Result: Success0
RESULT: 57==>True
Context file '/tmp/tmpjdjgh435/include/copy_evens.h' created.
Test file '/tmp/tmpjdjgh435/test/test_main.cu' created.
Solution file '/tmp/tmpjdjgh435/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpjdjgh435/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpjdjgh435/test.out'.
[Task_58] Execution Result: Success0
RESULT: 58==>True
Context file '/tmp/tmpydbytcvt/include/has_negatives.h' created.
Test file '/tmp/tmpydbytcvt/test/test_main.cu' created.
Solution file '/tmp/tmpydbytcvt/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpydbytcvt/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmpydbytcvt/test.out'.
[Task_59] Execution Result: Success0
RESULT: 59==>True
Context file '/tmp/tmpra0pu4bp/include/only_common.h' created.
Test file '/tmp/tmpra0pu4bp/test/test_main.cu' created.
Solution file '/tmp/tmpra0pu4bp/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpra0pu4bp/solution.cu test/*.cu'.
Test with '/tmp/tmpra0pu4bp/test.out'.
[Task_60] Execution Result: Success0
RESULT: 60==>True
Context file '/tmp/tmpn4hwitof/include/extrema.h' created.
Test file '/tmp/tmpn4hwitof/test/test_main.cu' created.
Solution file '/tmp/tmpn4hwitof/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpn4hwitof/solution.cu test/*.cu'.
Test with '/tmp/tmpn4hwitof/test.out'.
[Task_61] Execution Result: Success0
RESULT: 61==>True
Context file '/tmp/tmpn5pk2bsm/include/combine.h' created.
Test file '/tmp/tmpn5pk2bsm/test/test_main.cu' created.
Solution file '/tmp/tmpn5pk2bsm/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmpn5pk2bsm/solution.cu test/*.cu'.
Test with '/tmp/tmpn5pk2bsm/test.out'.
[Task_62] Execution Result: Success0
RESULT: 62==>True
Context file '/tmp/tmp3lpg99b5/include/no_positives.h' created.
Test file '/tmp/tmp3lpg99b5/test/test_main.cu' created.
Solution file '/tmp/tmp3lpg99b5/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp3lpg99b5/solution.cu test/*.cu --extended-lambda'.
Test with '/tmp/tmp3lpg99b5/test.out'.
[Task_63] Execution Result: Success0
RESULT: 63==>True
Context file '/tmp/tmpj7_dug9x/include/reduce_chunks.h' created.
Test file '/tmp/tmpj7_dug9x/test/test_main.cu' created.
Solution file '/tmp/tmpj7_dug9x/solution.cu' created.

In [ ]:
evaluation_result

[{'status': True, 'task_id': '146', 'reason': 'Test Passed'},
 {'status': True, 'task_id': '151', 'reason': 'Test Passed'}]

In [35]:
import pandas as pd

solution_df = pd.read_parquet("hf://datasets/Xueyan/cudasolution/data/train-00000-of-00001.parquet")

In [38]:
solution_df.head(1)

,type,schema_version,task_id,date,prompt,metadata,group,context_files,test_files,source_references,build_command,test_command,benchmark_command,timing_mode,min_cuda_toolkit,compute_capability,requires_datacenter_gpu,timeout_seconds,baseline_solution,generated_response
0,cuda_cpp,2,CUDA/146,1761868800000,Develop a CUDA program using the Thrust API to...,"{'difficulty': 'medium', 'tags': ['thrust', 'b...",cccl,"[{'path': 'include/find_indices.h', 'content':...","[{'path': 'test/test_main.cu', 'content': '#in...",None,nvcc -I include -o test.out solution.cu test/*.cu,./test.out,./test.out --perf,"{'type': 'region', 'include': ['bench_region']...",12.2,NaN,False,120,"{'schema_version': 1, 'type': 'file', 'task_id...","```cpp\n// solution.cu\n\n#include ""include/fi..."

In [51]:
filtered_solution = solution_df[solution_df['generated_response'] != 'nan']

In [52]:
len(filtered_solution)

169

In [80]:
def clean_code(generated_cuda_code: str) -> str:
  generated_cuda_code = filtered_solution['generated_response'][0]
  generated_cuda_code = generated_cuda_code.replace('```cpp\n', '').replace('```cuda\n', '').replace('```python\n', '').replace('```\n', '')
  generated_cuda_code = generated_cuda_code.replace('\n```', '')
  generated_cuda_code = generated_cuda_code.replace('// solution.cu\n\n', '')
  return generated_cuda_code

In [81]:
pass_count = 0;
total_count = len(filtered_solution)
evaluation_results = []

for index, input_row in filtered_solution.iloc[0:1].iterrows():
  problem_row =input_row
  generated_response = input_row['generated_response']
  cleaned_response = clean_code(generated_response)
  result = evaluator(input_row['task_id'], cleaned_response, '', input_row['context_files'], input_row['test_files'], input_row['build_command'], input_row['test_command'])
  print("RESULT: " + result['task_id'] + '==>' + str(result['status']))
  evaluation_results.append(result)
  if result['status']:
    pass_count+=1

evaluation_df = pd.DataFrame(evaluation_results)
print("\nEvaluation Summary:")
print(evaluation_df)
print('Accumulated accuracy ==>' + str(pass_count/total_count * 100) + '%')


evaluation_df.to_csv('evaluation_results.csv', index=False)
from google.colab import files
files.download('evaluation_results.csv')
print("evaluation_df saved to evaluation_results.csv")

Context file '/tmp/tmp2hjyvqsg/include/find_indices.h' created.
Test file '/tmp/tmp2hjyvqsg/test/test_main.cu' created.
Solution file '/tmp/tmp2hjyvqsg/solution.cu' created.
Compile with 'nvcc -I include -o test.out /tmp/tmp2hjyvqsg/solution.cu test/*.cu'.
Test with '/tmp/tmp2hjyvqsg/test.out'.
[Task_146] Execution Result: Success0
RESULT: 146==>True

Evaluation Summary:
   status task_id       reason
0    True     146  Test Passed
Accumulated accuracy ==>0.591715976331361%

evaluation_df saved to evaluation_results.csv

## LLM-as-a-judge Evaluator

In [ ]:
## Prompt

In [131]:
from google.colab import userdata
import os

# Retrieve credentials from Secrets Manager
token = userdata.get('GITHUB_TOKEN')
username = "xxueewa"
repo_name = "labscripts"

# Configure Git user details
!git config --global user.name "{username}"
!git config --global user.email "xueyanwapply@gmail.com"

# Clone the repository if it doesn't already exist
# Clone using the standard HTTPS URL first
if not os.path.exists(repo_name):
  print(f"Cloning repository 'https://github.com/{username}/{repo_name}.git'")
  !git clone https://github.com/{username}/{repo_name}.git
else:
  print(f"Directory '{repo_name}' already exists. Skipping clone.")

Cloning repository 'https://github.com/xxueewa/labscripts.git'
Cloning into 'labscripts'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), 4.75 KiB | 4.75 MiB/s, done.

In [130]:
!ls -a

.  ..  .config	evaluation_results.csv	sample_data

In [129]:
!rm -r labscripts

In [133]:
import os
os.chdir('labscripts')

In [138]:
# Set the remote origin URL to include the Personal Access Token for authentication
!git remote set-url origin https://{username}:{token}@github.com/{username}/{repo_name}.git
print("Remote origin URL updated with token for authentication.")

Remote origin URL updated with token for authentication.

In [127]:
import os
os.chdir('..')

In [140]:
!git add .

In [135]:
!git commit -m "init"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [122]:
!git config --list

filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=xxueewa
user.email=xueyanwapply@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/xxueewa/labscripts.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main

In [136]:
!git remote -v

origin	https://github.com/xxueewa/labscripts.git (fetch)
origin	https://github.com/xxueewa/labscripts.git (push)

In [139]:
!git push

Everything up-to-date

In [141]:
import os
from google.colab import drive

# Mount Google Drive to access the current notebook file
drive.mount('/content/drive')

# Get the path of the current notebook
notebook_path = '/content/drive/My Drive/Colab Notebooks/' + os.path.basename(__file__)

# Change to the labscripts directory to save the notebook there
os.chdir('/content/labscripts')

# Save the current notebook to the labscripts directory
!cp "{notebook_path}" .

# Add the notebook to git
notebook_filename = os.path.basename(notebook_path)
!git add "{notebook_filename}"
print(f"Notebook '{notebook_filename}' added to git staging area.")

Mounted at /content/drive

NameError: name '__file__' is not defined